[package]
name = "transaction_types"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "transaction_types"

[dependencies]
hdi = { workspace = true }
hdk = { workspace = true }

serde = { workspace = true }
